#!/bin/sh
set -e

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904 # initial commit; diff against an empty tree object
fi

allownonascii=$(git config --bool hooks.allownonascii)

# redirect output to stderr

exec 1>&2

if [ "$allownonascii" != "true" ] && test $(git diff --cached --name-only --diff-filter=A -z $against | LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0; then
	echo "Tryna add non-ASCII filenames"
	exit 1
fi

# make sure '.flaskenv' was not accidentally staged (e.g. by running 'git add .')

git reset -- .flaskenv

# if there are terminating whitespaces, print the offending file names and fail

exec git diff-index --check --cached $against --
