# editorconfig-checker-disable-file
#
# File based on the "Deploy a Python app to an Azure Web App" action by Microsoft

name: 'Build and deploy Python app to Azure Web App'

env:
  AZURE_WEBAPP_NAME: statify-sinf
  PYTHON_VERSION: '3.9'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set up Python version'
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Create and start virtual environment'
        run: |
          python -m venv env
          source env/bin/activate

      - name: 'Install dependencies'
        run: pip install -r requirements.txt

      - name: 'Generate database'
        run: flask init-db

      - name: 'Upload artifact for deployment jobs'
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !env/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Deployment'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
