# editorconfig-checker-disable-file

name: Tests

on:
  push:
    paths-ignore:
      - .git-template/**
      - README.md

jobs:
  test:

    name: Test application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest editorconfig-checker

      - name: Test with editorconfig-checker
        run: ec -config .editorconfig

      - name: Generate database
        run: flask init-db

      - name: Test with pytest
        run: pytest tests
